import { CategoryItem } from './types';

export const GENRES: CategoryItem[] = [
  { id: 'indie', label: 'Indie', description: '독창적이고 비주류적인 사운드를 가진 독립 음악입니다.' },
  { id: 'rnb', label: 'RnB', description: '소울풀한 보컬과 그루브에 집중한 리듬 앤 블루스입니다.' },
  { id: 'lofi', label: 'Lofi', description: '편안하고 아늑한 분위기의 로우파이 비트입니다.' },
  { id: 'ambient', label: 'Ambient', description: '공간감과 분위기에 집중한 잔잔한 배경 음악입니다.' },
  { id: 'folk', label: 'Folk', description: '이야기 전달을 중심으로 하는 전통적인 어쿠스틱 음악입니다.' },
  { id: 'ballad', label: 'Ballad', description: '사랑이나 이별을 주제로 한 감성적이고 느린 템포의 곡입니다.' },
  { id: 'jazz', label: 'Jazz', description: '복잡한 화성과 즉흥적인 리듬이 특징인 음악입니다.' },
  { id: 'acoustic', label: 'Acoustic', description: '자연 악기를 사용한 언플러그드 음악입니다.' },
  { id: 'dance', label: 'Dance', description: '움직임과 클럽 분위기를 위해 설계된 비트 중심의 음악입니다.' },
  { id: 'rock', label: 'Rock', description: '전기 기타와 드럼이 주도하는 에너지 넘치는 음악입니다.' },
  { id: 'punk', label: 'Punk', description: '빠른 템포와 가공되지 않은 반항적인 에너지의 음악입니다.' },
  { id: 'metal', label: 'Metal', description: '강력한 리듬과 왜곡된 사운드의 헤비한 음악입니다.' },
  { id: 'soul', label: 'Soul', description: '복음성가에 뿌리를 둔 깊은 감정 표현의 음악입니다.' },
  { id: 'hiphop', label: 'Hip-Hop', description: '리드미컬한 비트와 스타일리시한 랩이 조화된 음악입니다.' },
  { id: 'edm', label: 'EDM', description: '고에너지 환경을 위한 전자 댄스 음악입니다.' },
  { id: 'latin', label: 'Latin', description: '라틴 아메리카 문화의 리듬과 스타일을 담은 음악입니다.' },
  { id: 'reggae', label: 'Reggae', description: '자메이카 특유의 엇박자 리듬과 여유로운 분위기입니다.' },
  { id: 'funk', label: 'Funk', description: '베이스와 드럼이 강조된 강력한 리듬 그루브 음악입니다.' },
  { id: 'house', label: 'House', description: '반복적인 4/4 비트와 전자적 질감의 음악입니다.' },
  { id: 'blues', label: 'Blues', description: '블루스 스케일과 코드를 기반으로 한 감정 표현 음악입니다.' },
  { id: 'rap', label: 'Rap', description: '강렬한 비트 위에 리드미컬한 가사 전달이 특징인 음악입니다.' },
  { id: 'techno', label: 'Techno', description: '반복적인 비트와 전자적인 사운드가 특징인 테크노 음악입니다.' },
  { id: 'kpop', label: 'K-Pop', description: '한국의 대중음악으로, 다양한 장르가 혼합된 세련된 사운드입니다.' },
  { id: 'synth', label: 'Synth', description: '신시사이저 사운드가 주도하는 전자 음악입니다.' },
  { id: 'pop', label: 'Pop', description: '대중적이고 캐치한 멜로디의 현대적인 음악입니다.' },
  { id: 'electronic', label: 'Electronic', description: '전자 악기와 기술을 활용한 현대적인 사운드입니다.' },
  { id: 'piano', label: 'Piano', description: '피아노 선율이 중심이 되는 서정적인 음악입니다.' },
  { id: 'newage', label: 'New Age', description: '명상과 휴식을 위한 평온하고 조화로운 음악입니다.' },
  { id: 'country', label: 'Country', description: '미국 전통 음악에 뿌리를 둔 소박하고 진솔한 음악입니다.' },
  { id: 'traditional-trot', label: 'Traditional Trot', description: '한국 전통 트로트의 깊은 감성과 꺾기 창법이 특징입니다.' },
  { id: 'semi-trot', label: 'Semi-Trot', description: '현대적인 감각이 더해진 경쾌하고 대중적인 트로트입니다.' },
];

export const MOODS: CategoryItem[] = [
  { id: 'cool', label: 'Cool', description: '시원하고 세련된 분위기입니다.' },
  { id: 'chill', label: 'Chill', description: '느긋하고 편안한 무드입니다.' },
  { id: 'calm', label: 'Calm', description: '차분하고 고요한 느낌을 줍니다.' },
  { id: 'cheerful', label: 'Cheerful', description: '밝고 쾌활하며 즐거운 분위기입니다.' },
  { id: 'cinematic', label: 'Cinematic', description: '영화의 한 장면 같은 웅장하거나 서사적인 느낌입니다.' },
  { id: 'mellow', label: 'Mellow', description: '부드럽고 풍부하며 편안한 사운드입니다.' },
  { id: 'coziness', label: 'Coziness', description: '포근하고 아늑한 느낌을 줍니다.' },
  { id: 'nostalgic', label: 'Nostalgic', description: '과거에 대한 향수와 그리움을 불러일으킵니다.' },
  { id: 'dreamy', label: 'Dreamy', description: '꿈결 같은 몽환적이고 신비로운 분위기입니다.' },
  { id: 'romantic', label: 'Romantic', description: '낭만적이고 사랑스러운 감정을 담았습니다.' },
  { id: 'peaceful', label: 'Peaceful', description: '평화롭고 고요한 마음의 안정을 줍니다.' },
  { id: 'healing', label: 'Healing', description: '지친 마음을 달래주는 치유의 사운드입니다.' },
  { id: 'bright', label: 'Bright', description: '빛나고 화사하며 긍정적인 에너지입니다.' },
  { id: 'emotional', label: 'Emotional', description: '깊은 감동과 풍부한 감정 표현이 특징입니다.' },
  { id: 'minimalist', label: 'Minimalist', description: '단순함의 미학을 살린 절제된 사운드입니다.' },
  { id: 'melancholic', label: 'Melancholic', description: '애수 어린 슬픔과 깊은 성찰의 분위기입니다.' },
  { id: 'bittersweet', label: 'Bittersweet', description: '달콤하면서도 쌉싸름한 복합적인 감정입니다.' },
  { id: 'groovy', label: 'Groovy', description: '리드미컬하고 몸을 들썩이게 하는 그루브입니다.' },
  { id: 'upbeat', label: 'Upbeat', description: '박동감 넘치고 활기찬 리듬입니다.' },
  { id: 'funky', label: 'Funky', description: '강렬한 리듬감과 개성 있는 사운드입니다.' },
  { id: 'powerful', label: 'Powerful', description: '강력하고 힘 있는 에너지의 사운드입니다.' },
  { id: 'urban', label: 'Urban', description: '세련된 도시적 감성과 현대적인 바이브입니다.' },
  { id: 'sophisticated', label: 'Sophisticated', description: '교양 있고 세련된 고품격 사운드입니다.' },
  { id: 'atmospheric', label: 'Atmospheric', description: '공간감과 분위기가 강조된 오묘한 느낌입니다.' },
  { id: 'moody', label: 'Moody', description: '변덕스럽거나 깊은 분위기를 자아내는 무드입니다.' },
  { id: 'infectious', label: 'Infectious', description: '한 번 들으면 잊히지 않는 중독성 있는 사운드입니다.' },
  { id: 'hypnotic', label: 'Hypnotic', description: '최면에 걸린 듯 빠져드는 반복적인 매력입니다.' },
  { id: 'zen', label: 'Zen', description: '명상적이고 정신적인 평온함을 주는 사운드입니다.' },
  { id: 'loneliness', label: 'Loneliness', description: '고독하고 쓸쓸한 감정의 깊이를 담았습니다.' },
];

export const THEMES: CategoryItem[] = [
  { id: 'love', label: '사랑', description: '애정과 깊은 유대감을 다룹니다.' },
  { id: 'breakup', label: '이별', description: '헤어짐과 상실의 아픔을 노래합니다.' },
  { id: 'longing', label: '그리움', description: '과거에 대한 그리움과 향수를 담았습니다.' },
  { id: 'hope', label: '희망', description: '더 나은 내일을 향한 기대를 담았습니다.' },
  { id: 'city', label: '도시', description: '활기찬 도시 풍경 속의 삶을 그립니다.' },
  { id: 'loneliness-theme', label: '외로움', description: '혼자 있는 느낌과 고독을 다룹니다.' },
  { id: 'fear', label: '두려움', description: '미지의 세계나 불안에 맞서는 감정입니다.' },
  { id: 'reminiscence', label: '회상', description: '추억을 되새기는 시간입니다.' },
  { id: 'weather', label: '날씨', description: '계절과 날씨가 주는 분위기를 담았습니다.' },
  { id: 'anger', label: '분노', description: '강한 불만이나 분노의 감정 표현입니다.' },
  { id: 'friendship', label: '우정', description: '동료들과의 유대와 우정을 다룹니다.' },
  { id: 'travel', label: '여행', description: '새로운 장소로 떠나는 여정입니다.' },
  { id: 'self', label: '자아', description: '나 자신을 찾아가는 내면의 여정입니다.' },
  { id: 'night', label: '밤', description: '밤 시간의 고요함이나 신비로움을 담았습니다.' },
  { id: 'curiosity', label: '호기심', description: '알고 싶고 배우고 싶은 욕구입니다.' },
  { id: 'after-work', label: '퇴근', description: '하루를 마친 후의 해방감과 안도감입니다.' },
  { id: 'time', label: '시간', description: '시간의 흐름과 가치에 대한 이야기입니다.' },
  { id: 'season', label: '계절', description: '자연과 계절의 변화를 노래합니다.' },
  { id: 'growth', label: '성장', description: '개인적인 발전과 변화의 과정입니다.' },
  { id: 'hobby', label: '취미', description: '좋아하는 일을 하며 느끼는 즐거움입니다.' },
  { id: 'weekend', label: '주말', description: '기다려온 주말의 설렘과 휴식입니다.' },
  { id: 'cafe', label: '카페', description: '커피 향과 함께하는 여유로운 시간입니다.' },
  { id: 'childhood', label: '어린시절', description: '순수했던 어린 시절의 추억과 향수입니다.' },
  { id: 'small-happiness', label: '소확행', description: '일상 속에서 느끼는 작지만 확실한 행복입니다.' },
  { id: 'haven', label: '안식처', description: '지친 몸과 마음을 쉴 수 있는 편안한 공간입니다.' },
  { id: 'comfort', label: '위로', description: '힘든 순간 따뜻하게 감싸주는 위로의 메시지입니다.' },
  { id: 'first-meeting', label: '첫만남', description: '처음 만났을 때의 설렘과 풋풋한 기억입니다.' },
  { id: 'freedom', label: '자유', description: '구속에서 벗어나 느끼는 해방감과 자유입니다.' },
  { id: 'destiny', label: '운명', description: '피할 수 없는 인연과 삶의 필연적인 흐름입니다.' },
  { id: 'stroll', label: '산책', description: '천천히 걸으며 느끼는 여유와 생각의 시간입니다.' },
  { id: 'obsession', label: '집착', description: '무언가에 강하게 매달리는 복잡한 심경입니다.' },
  { id: 'resistance', label: '저항', description: '주어진 상황이나 운명에 맞서는 강한 의지입니다.' },
  { id: 'family', label: '가족', description: '가장 가깝고 소중한 가족에 대한 사랑과 유대입니다.' },
  { id: 'regret', label: '후회', description: '지나간 일에 대한 아쉬움과 성찰의 감정입니다.' },
  { id: 'youth', label: '청춘', description: '뜨겁고 찬란하며 때로는 불안한 젊은 날의 기록입니다.' },
  { id: 'anxiety', label: '불안', description: '미래에 대한 걱정과 내면의 흔들림을 다룹니다.' },
  { id: 'unrequited-love', label: '짝사랑', description: '혼자만 간직한 애틋하고 아픈 사랑의 감정입니다.' },
  { id: 'hometown', label: '고향', description: '태어나고 자란 곳에 대한 그리움과 추억입니다.' },
  { id: 'living-away', label: '타향살이', description: '익숙하지 않은 곳에서 살아가는 외로움과 적응의 과정입니다.' },
];

export const BASE_PROMPTS = [
  "IndieR&B song, slow tempo around 82 BPM, Intro begins with minimal electric piano notes and subtle city ambience before warm Rhodes chords gradually enter, Soft fingerpicked acoustic guitar appears later in the arrangement, Smooth subtle bass line with extremely minimal brushed snare or nearly absent percussion, Warm acoustic guitar supporting the harmony, relaxed arrangement designed for reading, walking, and background listening, Mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, Vocal melody should stay in a comfortable mid-range with restrained storytelling vocal delivery, Warm natural mix with light reverb, no dramatic build-up, no explosive climax, Target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "IndieFolk song, slow tempo around 72–76 BPM, intro begins with gentle fingerpicked acoustic guitar alone before soft piano textures enter, warm acoustic guitar as the main instrument, subtle piano layers and soft bass support, extremely minimal percussion or nearly absent drums, relaxed arrangement suitable for reading, studying, and background listening, mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, restrained storytelling vocal delivery, warm natural mix with light reverb, reflective nostalgic mood, no dramatic build-up, no explosive climax, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "IndieR&B song with a calm and warm atmosphere suitable for background listening, slow tempo around 76–80 BPM, intro begins with gentle Rhodes chords followed by soft acoustic guitar layers, smooth subtle bass line, extremely minimal brushed snare or nearly absent percussion, relaxed arrangement designed for reading, studying, and walking, mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, restrained emotional delivery, warm natural mix with light reverb, peaceful reflective mood, no dramatic build-up, no explosive climax, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "IndieFolk song for a calm late-night reflective atmosphere, slow tempo around 72–76 BPM, intro begins with gentle piano notes followed by soft fingerpicked acoustic guitar, warm acoustic guitar as the main instrument, subtle piano textures and soft bass support, extremely minimal percussion or nearly absent drums, relaxed arrangement designed for reading, studying, and background listening, mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, restrained storytelling vocal delivery, warm natural mix with light reverb, reflective and peaceful mood, no dramatic build-up, no explosive climax, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Soft indieR&B pop, bright calm mood, 72–76 BPM, acoustic fingerpicking guitar lead, light piano accents, minimal brush drums, soft bass, airy ambient pads, intimate conversational vocal tone, no high notes, gentle reflective atmosphere, smooth flowing arrangement, warm natural mix, soft reverb, gentle fade-out ending, theme: quiet weekend afternoon noticing small changes in everyday life, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Soft indie pop, 76-80 BPM, warm acoustic guitar lead, light felt piano accents, gentle bass, minimal brush drums, airy ambient pads, reflective bus ride atmosphere, intimate soft vocal tone, no high notes, smooth flowing arrangement, warm sunset mood, natural mix, soft reverb, gentle fade-out ending, theme: watching the world through a bus window and quietly feeling a new beginning, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Soft indie folk, 74 BPM, warm acoustic guitar picking, light piano textures, gentle bass, minimal brush drums, calm evening walk atmosphere, reflective male vocal tone, storytelling delivery, no high notes, smooth flowing arrangement, warm natural mix, soft reverb, gentle fade-out ending, theme: pretending nothing changed while quietly realizing something did, target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Acoustic R&B with indie pop elements, bright and rhythmic groove, 92–98 BPM, warm acoustic guitar strumming, soft muted electric guitar riffs, Subtle bass groove, light percussive drums with rim clicks and soft snare, Gradual instrument layering from minimal guitar to full band in final chorus, Emotional but controlled vocal delivery (no excessive falsetto), Catchy and repetitive chorus hook, warm and uplifting atmosphere, Target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, Intimate yet cinematic build-up, Soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, Restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Acoustic R&B with indie pop elements, bright and rhythmic groove, 92–98 BPM, warm acoustic guitar strumming, soft muted electric guitar riffs, Subtle bass groove, light percussive drums with rim clicks and soft snare, Gradual instrument layering from minimal guitar to full band in final chorus, Emotional but controlled vocal delivery (no excessive falsetto), Catchy and repetitive chorus hook, warm and uplifting atmosphere, Intimate yet cinematic build-up, final chorus with added harmonies and fuller drums, then gradually fading into a calm and quiet ending, Target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, Intimate yet cinematic build-up, Soft and intimate outro, minimal instrumentation, gradual instrumental fade-out, Restrained vocal delivery, no dramatic ending, fade gently into silence",
  "Acoustic R&B ballad with indie pop elements, slow tempo around 74–80 BPM, Warm acoustic guitar arpeggios, soft piano or Rhodes textures, Smooth subtle bass line, very light brushed snare or minimal percussion, No dramatic build-up, no explosive climax, Mid-range focused melody, limited vocal range, no high belting, no vocal peaks, no falsetto, Warm natural mix with light reverb, no dramatic build-up, no explosive climax, Soft chest-dominant vocal tone, restrained and steady emotional delivery, Concise arrangement, no extended intro, no repeated extra chorus, tight structure, Smooth ending, Target song length between 2 minutes 40 seconds and 3 minutes 10 seconds",
  "Soulful Deep Vocals, Gritty Neo-soul, Gospel-inflected harmonies, Velvety Rich Texture, Melismatic Ad-libs, Jazzhop, Chillhop, Clean Chorus Electric Guitar, Soft Rhodes Piano, Mellow Walking Bassline, Steady Boom-bap Beat, Sophisticated Urban Vibe, 85 BPM, High Fidelity, Analog Warmth, Extended Length, Target song length between 2 minutes 40 seconds and 3 minutes 10 seconds",
  "Groovy indie pop with smooth rhythmic flow, 96 BPM, warm and intimate male vocal with calm confidence, clean electric guitar with muted funky strumming, round groovy bassline with subtle slides, tight minimal drums, soft snare, light 16th hi-hats, bright morning atmosphere with gentle sunlight feeling, uplifting but emotionally restrained, lyrics about starting over, first light, fresh air, taking steps forward, hopeful and steady mood, modern indie production, radio edit length under 3 minutes 40 seconds",
  "Minimal groovy indie pop with subtle emotional lift, 95 BPM, Warm intimate vocal, steady round bassline, Clean muted electric guitar rhythm, tight minimal drums with soft hi-hats, Calm but confident mood, theme of quiet growth and self-belief, No dramatic climax, smooth build in final chorus, Target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, clean modern mix, Soft and intimate outro, minimal instrumentation, gradual instrumental fade-out,",
  "Soft urban indie pop, calm and reflective mood, 76–78 BPM, G major, Low, calm male vocal (hoodie persona), intimate and restrained, no belting, grounded delivery, Clean electric guitar with light reverb arpeggios (slightly more prominent than acoustic), Minimal brush drums steady from early verse, warm bass slightly, No glockenspiel, subtle city-night ambient texture, Arrangement steady and minimal, chorus slightly wider but not bigger in volume, Warm natural mix, soft reverb, gentle fade ending, Target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, clean modern mix, Soft and intimate outro, minimal instrumentation, gradual instrumental fade-out",
  "Upbeat urban groovy indie pop, 110 BPM, cool confident vocal, driving funky bassline, muted rhythmic electric guitar, tight punchy drums with crisp hi-hats and claps, night drive city vibe, energetic but stylish mood, radio edit format, clear strong ending, length strictly under 3 minutes, no extended instrumental sections, do not loop endlessly",
  "Indie Groove, Jazzhop fusion, Clean electric guitar, Deep groovy bassline, Mid-tempo 92 BPM, Smooth Fender Rhodes, Crisp drums, No hiss, High-fidelity, Professional mixing, Atmospheric and Inspiring, Extended structure",
  "A bright, soft acoustic R&B pop with a sunny and cozy atmosphere, Features sweet, rhythmic acoustic guitar strumming and a mellow, organic Rhodes piano for a fresh and inviting mood, The tempo is 78 BPM, relaxed but with a light, walking-paced groove, Playful, melodic bassline and crisp finger snaps mixed with a soft shaker rhythm, Chorus blooms with airy, delicate string swells and subtle, high-register acoustic guitar harmonics that add a touch of elegance, The sound is clean, spacious, and high-fidelity, avoiding any sharp or metallic tones, The arrangement is minimal yet polished, easing into a gentle guitar and a soft, warm pad synth outro that leaves a cheerful, lingering sweetness, Romantic, sophisticated, sunny afternoon cafe vibe, instrumental, no explosive climax. Target song length between 2 minutes 40 seconds and 3 minutes 10 seconds, clean modern mix, Soft and intimate outro, minimal instrumentation, gradual instrumental fade-out",
];
